apiVersion: v1
kind: ConfigMap
metadata:
  name: web-service
data:
  application.yml: |-
    pivotal:
      quotesService:
        name: quotes-service
      userService:
        name: user-service  
      accountsService:
        name: accounts-service
      portfolioService:
        name: portfolio-service
      analyticsService:
        name: analytics-service
    logging:
      level:
         io:
            pivotal: DEBUG
         com:
            netflix: FATAL
         org:
            springframework:
               web: WARN
               cloud: WARN
    spring:
      sleuth:
        sampler:
          probability: 1.0
    management:
      endpoints:
        web:
          exposure:
            include: "*"
    spring:
      security:
        oauth2:
          client:
            registration:
              uaa: 
                client-id: tanzu_zoneadmin
                client-secret: tanzu
                scope: scope=resource.read,resource.write,openid,profile
            provider:
              issuer-uri: https://uaa.cf4k8s.wrightcode.io/oauth/token